-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- 1. Organizations (Tenants)
-- CREATE TABLE public.organizations (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     name TEXT NOT NULL,
--     quota_allowed INT NOT NULL DEFAULT 100,
--     quota_used INT NOT NULL DEFAULT 0,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
--
-- -- 2. Organization Members
-- CREATE TABLE public.org_members (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
--     user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
--     role TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'viewer')),
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--     UNIQUE (org_id, user_id)
-- );
--
-- -- 3. Workflows
-- CREATE TABLE public.workflows (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
--     name TEXT NOT NULL,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
--
-- -- 4. Workflow Triggers
-- CREATE TABLE public.workflow_triggers (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     workflow_id UUID NOT NULL REFERENCES public.workflows(id) ON DELETE CASCADE,
--     type TEXT NOT NULL CHECK (type IN ('manual', 'webhook', 'scheduled', 'database_event')),
--     config JSONB DEFAULT '{}'::jsonb,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
--
-- -- 5. Workflow Steps
-- CREATE TABLE public.workflow_steps (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     workflow_id UUID NOT NULL REFERENCES public.workflows(id) ON DELETE CASCADE,
--     order_index INT NOT NULL,
--     type TEXT NOT NULL CHECK (type IN ('llm_call', 'http_request', 'db_write', 'notify', 'conditional_branch', 'approval_gate')),
--     config JSONB DEFAULT '{}'::jsonb,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--     UNIQUE (workflow_id, order_index)
-- );
--
-- -- 6. Workflow Runs
-- CREATE TABLE public.workflow_runs (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     workflow_id UUID NOT NULL REFERENCES public.workflows(id) ON DELETE CASCADE,
--     status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'paused', 'completed', 'failed')),
--     started_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--     completed_at TIMESTAMPTZ
-- );
--
-- -- 7. Step Runs
-- CREATE TABLE public.step_runs (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     workflow_run_id UUID NOT NULL REFERENCES public.workflow_runs(id) ON DELETE CASCADE,
--     step_id UUID NOT NULL REFERENCES public.workflow_steps(id) ON DELETE CASCADE,
--     status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'paused_awaiting_approval', 'completed', 'failed')),
--     input_data JSONB,
--     output_data JSONB,
--     error_message TEXT,
--     attempt_count INT NOT NULL DEFAULT 1,
--     approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
--     approved_at TIMESTAMPTZ,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--     completed_at TIMESTAMPTZ
-- );
